/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RedisIndexRouteImport } from './routes/redis/index'
import { Route as RedisSandboxIdRouteImport } from './routes/redis/sandbox.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedisIndexRoute = RedisIndexRouteImport.update({
  id: '/redis/',
  path: '/redis/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedisSandboxIdRoute = RedisSandboxIdRouteImport.update({
  id: '/redis/sandbox/$id',
  path: '/redis/sandbox/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/redis/': typeof RedisIndexRoute
  '/redis/sandbox/$id': typeof RedisSandboxIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/redis': typeof RedisIndexRoute
  '/redis/sandbox/$id': typeof RedisSandboxIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/redis/': typeof RedisIndexRoute
  '/redis/sandbox/$id': typeof RedisSandboxIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/redis/' | '/redis/sandbox/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/redis' | '/redis/sandbox/$id'
  id: '__root__' | '/' | '/redis/' | '/redis/sandbox/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RedisIndexRoute: typeof RedisIndexRoute
  RedisSandboxIdRoute: typeof RedisSandboxIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redis/': {
      id: '/redis/'
      path: '/redis'
      fullPath: '/redis/'
      preLoaderRoute: typeof RedisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redis/sandbox/$id': {
      id: '/redis/sandbox/$id'
      path: '/redis/sandbox/$id'
      fullPath: '/redis/sandbox/$id'
      preLoaderRoute: typeof RedisSandboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RedisIndexRoute: RedisIndexRoute,
  RedisSandboxIdRoute: RedisSandboxIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
