/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WadIndexRouteImport } from './routes/wad/index'
import { Route as RedisIndexRouteImport } from './routes/redis/index'
import { Route as PlcIndexRouteImport } from './routes/plc/index'
import { Route as WadWorkspaceIdRouteImport } from './routes/wad/$workspaceId'
import { Route as RedisWorkspaceIdRouteImport } from './routes/redis/$workspaceId'
import { Route as PlcWorkspaceIdRouteImport } from './routes/plc/$workspaceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WadIndexRoute = WadIndexRouteImport.update({
  id: '/wad/',
  path: '/wad/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedisIndexRoute = RedisIndexRouteImport.update({
  id: '/redis/',
  path: '/redis/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlcIndexRoute = PlcIndexRouteImport.update({
  id: '/plc/',
  path: '/plc/',
  getParentRoute: () => rootRouteImport,
} as any)
const WadWorkspaceIdRoute = WadWorkspaceIdRouteImport.update({
  id: '/wad/$workspaceId',
  path: '/wad/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const RedisWorkspaceIdRoute = RedisWorkspaceIdRouteImport.update({
  id: '/redis/$workspaceId',
  path: '/redis/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlcWorkspaceIdRoute = PlcWorkspaceIdRouteImport.update({
  id: '/plc/$workspaceId',
  path: '/plc/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plc/$workspaceId': typeof PlcWorkspaceIdRoute
  '/redis/$workspaceId': typeof RedisWorkspaceIdRoute
  '/wad/$workspaceId': typeof WadWorkspaceIdRoute
  '/plc/': typeof PlcIndexRoute
  '/redis/': typeof RedisIndexRoute
  '/wad/': typeof WadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plc/$workspaceId': typeof PlcWorkspaceIdRoute
  '/redis/$workspaceId': typeof RedisWorkspaceIdRoute
  '/wad/$workspaceId': typeof WadWorkspaceIdRoute
  '/plc': typeof PlcIndexRoute
  '/redis': typeof RedisIndexRoute
  '/wad': typeof WadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plc/$workspaceId': typeof PlcWorkspaceIdRoute
  '/redis/$workspaceId': typeof RedisWorkspaceIdRoute
  '/wad/$workspaceId': typeof WadWorkspaceIdRoute
  '/plc/': typeof PlcIndexRoute
  '/redis/': typeof RedisIndexRoute
  '/wad/': typeof WadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plc/$workspaceId'
    | '/redis/$workspaceId'
    | '/wad/$workspaceId'
    | '/plc/'
    | '/redis/'
    | '/wad/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plc/$workspaceId'
    | '/redis/$workspaceId'
    | '/wad/$workspaceId'
    | '/plc'
    | '/redis'
    | '/wad'
  id:
    | '__root__'
    | '/'
    | '/plc/$workspaceId'
    | '/redis/$workspaceId'
    | '/wad/$workspaceId'
    | '/plc/'
    | '/redis/'
    | '/wad/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlcWorkspaceIdRoute: typeof PlcWorkspaceIdRoute
  RedisWorkspaceIdRoute: typeof RedisWorkspaceIdRoute
  WadWorkspaceIdRoute: typeof WadWorkspaceIdRoute
  PlcIndexRoute: typeof PlcIndexRoute
  RedisIndexRoute: typeof RedisIndexRoute
  WadIndexRoute: typeof WadIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wad/': {
      id: '/wad/'
      path: '/wad'
      fullPath: '/wad/'
      preLoaderRoute: typeof WadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redis/': {
      id: '/redis/'
      path: '/redis'
      fullPath: '/redis/'
      preLoaderRoute: typeof RedisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plc/': {
      id: '/plc/'
      path: '/plc'
      fullPath: '/plc/'
      preLoaderRoute: typeof PlcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wad/$workspaceId': {
      id: '/wad/$workspaceId'
      path: '/wad/$workspaceId'
      fullPath: '/wad/$workspaceId'
      preLoaderRoute: typeof WadWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redis/$workspaceId': {
      id: '/redis/$workspaceId'
      path: '/redis/$workspaceId'
      fullPath: '/redis/$workspaceId'
      preLoaderRoute: typeof RedisWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plc/$workspaceId': {
      id: '/plc/$workspaceId'
      path: '/plc/$workspaceId'
      fullPath: '/plc/$workspaceId'
      preLoaderRoute: typeof PlcWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlcWorkspaceIdRoute: PlcWorkspaceIdRoute,
  RedisWorkspaceIdRoute: RedisWorkspaceIdRoute,
  WadWorkspaceIdRoute: WadWorkspaceIdRoute,
  PlcIndexRoute: PlcIndexRoute,
  RedisIndexRoute: RedisIndexRoute,
  WadIndexRoute: WadIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
